13 feature data access classes
CSC207-2022F-UofT/course-project-team-bbq pull request #25
Opened 2022-11-13 19:19 UTC by jempio

2022-11-13 20:08 UTC, lucasprates74 approved these changes
what is done so far looks good. look into not having to rewrite the entire csv if possible

2022-11-14 21:02 UTC, Junyu11111 requested changes
Add a method to get the last ID in FlashcardDataAccess and FlashcardSetDataAccess.

2022-11-14 21:03 UTC, ThomasShimUoft requested changes
Implement FlashcardSetDataAccess Methods.

2022-11-15 02:17 UTC, uoftguy reviewed
For user, another attribute would be isAdmin, dictating whether or not an user has admin level access or not, it would be between the user password and flashcardSetIds

2022-11-16 03:57 UTC, uoftguy commented on src/main/java/dataAccess/CommonUserDataAccess.java
> +                String line = String.format("%s", "%s", "%s", "%s", user.getUsername(), user.getPassword(), user.getFlashcardSetIds());
Need to add user.getIsAdmin

2022-11-16 22:55 UTC, ThomasShimUoft approved these changes

2022-11-16 23:20 UTC, merged