Resolve the problem of creating duplicate flashcards with the same term.
CSC207-2022F-UofT/course-project-team-bbq pull request #92
Opened 2022-11-30 22:30 UTC by Junyu11111

As this may become a trouble for the test use case.

2022-12-01 19:08 UTC, Edward-1117 commented on src/main/java/create_flashcard_use_case/CreateFlashcardInteractor.java
> +        else if (gateway.getFlashcardSet(requestModel.getFlashcardSetId()) == null) {
Good change here to use gateway instead of fcDataAccess.

2022-12-01 19:22 UTC, Edward-1117 commented on src/main/java/create_flashcard_use_case/CreateFlashcardResponseModel.java
> +    public CreateFlashcardResponseModel(LocalDateTime creationDate, String term, String definition, int flashcardId) {
I think including the @param for the flashcard id in the Javadoc would be good.

2022-12-01 19:27 UTC, Edward-1117 requested changes
Looks like a good fix overall, nice job! One minor request is that I think you forgot the @param for the flashcard id in the Javadoc located in CreateFlashcardResponseModel.

2022-12-02 16:19 UTC, Junyu11111 commented
@Edward-1117 Thing should be fixed. Also, the presenter has been changed a bit.
Tests and documentation are added.

2022-12-02 18:22 UTC, Edward-1117 commented on src/main/java/create_flashcard_use_case/CreateFlashcardResponseModel.java
> +     * @param flashcardId flashcard id of the flashcard
Nice!

2022-12-02 18:24 UTC, Edward-1117 commented on src/main/java/create_flashcard_use_case/CreateFlashcardInteractor.java
> +     * Try to create a flashcard with the given term and definition in the given flashcard set,
Good documentation!

2022-12-02 18:26 UTC, Edward-1117 commented on src/main/java/delete_flashcard_use_case/DeleteFlashcardInteractor.java
> +     * Create DeleteFlashcardInteractor.
Good change here.

2022-12-02 18:30 UTC, Edward-1117 commented on src/main/java/interface_adapters/presenters/CreateFlashcardPresenter.java
> +     * @return the responseModel
Nice Javadocs!

2022-12-02 18:33 UTC, Edward-1117 commented on src/main/java/create_flashcard_use_case/CreateFlashcardInteractor.java
> +     * Try to create a flashcard with the given term and definition in the given flashcard set, recording the date of creation.
Good update to the Javadoc.

2022-12-02 18:43 UTC, Edward-1117 commented on src/main/java/interface_adapters/controllers/CreateFlashcardController.java
> +     * If flashcardId is -1, try to create a new flashcard.
Good documentation.

2022-12-02 19:07 UTC, Edward-1117 approved these changes

2022-12-02 19:11 UTC, merged